-- MySQL Script generated by MySQL Workbench
-- 02/19/15 17:30:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gtracer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gtracer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gtracer` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `gtracer` ;

-- -----------------------------------------------------
-- Table `gtracer`.`graduate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`graduate` (
  `student_no` VARCHAR(10) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `midname` VARCHAR(45) NULL DEFAULT NULL,
  `sex` VARCHAR(6) NOT NULL,
  `bdate` DATE NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `mobileno` VARCHAR(11) NOT NULL,
  `telno` INT(8) NULL DEFAULT NULL,
  `field` VARCHAR(45) NOT NULL,
  `major` VARCHAR(45) NULL DEFAULT NULL,
  `graduatedate` CHAR(7) NOT NULL,
  PRIMARY KEY (`student_no`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gtracer`.`ability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`ability` (
  `studentno` VARCHAR(10) NOT NULL,
  `ability` VARCHAR(45) NOT NULL COMMENT 'can be skill, talent, expertise',
  PRIMARY KEY (`studentno`, `ability`),
  CONSTRAINT `fk_ability_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `gtracer`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gtracer`.`association`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`association` (
  `studentno` VARCHAR(10) NOT NULL,
  `assocname` VARCHAR(60) NOT NULL COMMENT 'includes organizations/foundations, etc. ',
  PRIMARY KEY (`studentno`, `assocname`),
  CONSTRAINT `fk_association_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `gtracer`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gtracer`.`award`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`award` (
  `awardno` INT(11) NOT NULL AUTO_INCREMENT,
  `studentno` VARCHAR(10) NOT NULL,
  `awardtitle` VARCHAR(45) NOT NULL,
  `awardbody` VARCHAR(60) NULL DEFAULT NULL,
  `dategiven` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`awardno`, `studentno`),
  INDEX `fk_award_graduate1` (`studentno` ASC),
  CONSTRAINT `fk_award_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `gtracer`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gtracer`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`company` (
  `companyno` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`companyno`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gtracer`.`school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`school` (
  `schoolno` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`schoolno`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gtracer`.`educationalbg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`educationalbg` (
  `bgno` INT(11) NOT NULL AUTO_INCREMENT,
  `studentno` VARCHAR(10) NOT NULL,
  `school` INT(11) NOT NULL,
  `yearstart` YEAR NOT NULL,
  `yearend` YEAR NOT NULL,
  `level` VARCHAR(45) NOT NULL COMMENT 'primary, secondary, tertiary',
  `graduate` TINYINT(1) NOT NULL COMMENT '1 - graduated0 - not',
  `course` VARCHAR(45) NULL COMMENT 'if level is tertiary, course is required\n\nthis includes masters and doctorate degrees',
  PRIMARY KEY (`bgno`, `studentno`),
  INDEX `fk_educationalbg_school1_idx` (`school` ASC),
  INDEX `fk_educationalbg_graduate1` (`studentno` ASC),
  CONSTRAINT `fk_educationalbg_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `gtracer`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_educationalbg_school1`
    FOREIGN KEY (`school`)
    REFERENCES `gtracer`.`school` (`schoolno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gtracer`.`grant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`grant` (
  `studentno` VARCHAR(10) NOT NULL,
  `grantname` VARCHAR(45) NOT NULL,
  `grantor` VARCHAR(45) NULL DEFAULT NULL,
  `granttype` VARCHAR(45) NULL DEFAULT NULL COMMENT '* personal\n* government\n* others',
  `grantyear` YEAR NULL DEFAULT NULL COMMENT 'year effective of grant',
  PRIMARY KEY (`studentno`),
  CONSTRAINT `fk_grant_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `gtracer`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gtracer`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`language` (
  `studentno` VARCHAR(10) NOT NULL,
  `language` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`studentno`, `language`),
  CONSTRAINT `fk_language_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `gtracer`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gtracer`.`profexam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`profexam` (
  `studentno` VARCHAR(10) NOT NULL,
  `profexamname` VARCHAR(60) NOT NULL,
  `datetaken` DATE NOT NULL,
  `rating` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`studentno`, `profexamname`),
  CONSTRAINT `fk_profexam_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `gtracer`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gtracer`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`project` (
  `studentno` VARCHAR(10) NOT NULL,
  `projecttitle` VARCHAR(60) NOT NULL,
  `projectdesc` VARCHAR(300) NULL DEFAULT NULL,
  `datestart` DATE NULL DEFAULT NULL,
  `dateend` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`studentno`, `projecttitle`),
  CONSTRAINT `fk_project_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `gtracer`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gtracer`.`publication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`publication` (
  `publicationno` INT(11) NOT NULL AUTO_INCREMENT,
  `studentno` VARCHAR(20) NOT NULL,
  `publicationtitle` VARCHAR(60) NOT NULL,
  `publicationdate` DATE NOT NULL,
  `publicationdesc` VARCHAR(300) NULL DEFAULT NULL,
  `publicationbody` VARCHAR(45) NULL DEFAULT NULL,
  `publicationpeers` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`publicationno`, `studentno`),
  INDEX `fk_publication_graduate1` (`studentno` ASC),
  CONSTRAINT `fk_publication_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `gtracer`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gtracer`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`post` (
  `studentno` VARCHAR(10) NOT NULL,
  `postindex` INT(11) NULL DEFAULT NULL,
  `body` VARCHAR(512) NULL DEFAULT NULL,
  `time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`studentno`),
  CONSTRAINT `fk_update_graduate1`
    FOREIGN KEY (`studentno`)
    REFERENCES `gtracer`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gtracer`.`work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`work` (
  `workid` INT(11) NOT NULL AUTO_INCREMENT,
  `studentno` VARCHAR(10) NOT NULL,
  `companyno` INT(11) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `salary` INT(11) NULL DEFAULT NULL,
  `supervisor` TINYINT(1) NULL DEFAULT NULL,
  `companytype` TINYINT(1) NOT NULL COMMENT 'private-0 (including self-employed)\ngovernment-1',
  `employmentstatus` VARCHAR(45) NULL DEFAULT NULL COMMENT 'values check box on UI :)\nregular or permanent, temporary, casual, contractual, self-employed',
  `datestart` DATE NOT NULL,
  `dateend` DATE NOT NULL,
  PRIMARY KEY (`workid`, `studentno`),
  INDEX `fk_work_graduate_idx` (`studentno` ASC),
  INDEX `fk_company_companyno_idx` (`companyno` ASC),
  CONSTRAINT `fk_company_companyno`
    FOREIGN KEY (`companyno`)
    REFERENCES `gtracer`.`company` (`companyno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_work_graduate`
    FOREIGN KEY (`studentno`)
    REFERENCES `gtracer`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gtracer`.`connection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtracer`.`connection` (
  `student_no_1` VARCHAR(10) NOT NULL,
  `student_no_2` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`student_no_1`),
  INDEX `fk_connection_graduate_student_no_1_idx` (`student_no_2` ASC),
  CONSTRAINT `fk_connection_graduate_student_no_1`
    FOREIGN KEY (`student_no_1`)
    REFERENCES `gtracer`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_connection_graduate_student_no_2`
    FOREIGN KEY (`student_no_2`)
    REFERENCES `gtracer`.`graduate` (`student_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
