insert into (schoolno, name, address) values (1, 'University of the Philippines Los Banos', 'Los Banos, Laguna');
insert into (schoolno, name, address) values (2, 'Naga City Central School I', 'Penafrancia Avenue, Naga City');
insert into (schoolno, name, address) values (3, 'Kung Saan Mang School', NULL);
insert into (schoolno, name, address) values (4, 'Camarines Sur National High School', 'Penafrancia Avenue, Naga City');
insert into (schoolno, name, address) values (5, 'Santa Theresa College', 'Kap. Ponso St. Bauan Batangas');
insert into (schoolno, name, address) values (6, 'Good Tree International School', 'Bagtas Road, Brgy. Bagtas, Tansa Cavite');
insert into (schoolno, name, address) values (7, 'Missouri University', 'Missouri');
insert into (schoolno, name, address) values (8, 'Indiana University', 'Indiana');
insert into (schoolno, name, address) values (9, 'Kentucky University', 'Kentucky');
insert into (schoolno, name, address) values (10, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (11, 'Missouri University', 'Missouri');
insert into (schoolno, name, address) values (12, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (13, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (14, 'Nebraska University', 'Nebraska');
insert into (schoolno, name, address) values (15, 'West Virginia University', 'West Virginia');
insert into (schoolno, name, address) values (16, 'Indiana University', 'Indiana');
insert into (schoolno, name, address) values (17, 'Kentucky University', 'Kentucky');
insert into (schoolno, name, address) values (18, 'Connecticut University', 'Connecticut');
insert into (schoolno, name, address) values (19, 'Nevada University', 'Nevada');
insert into (schoolno, name, address) values (20, 'Nebraska University', 'Nebraska');
insert into (schoolno, name, address) values (21, 'West Virginia University', 'West Virginia');
insert into (schoolno, name, address) values (22, 'New York University', 'New York');
insert into (schoolno, name, address) values (23, 'New Mexico University', 'New Mexico');
insert into (schoolno, name, address) values (24, 'New York University', 'New York');
insert into (schoolno, name, address) values (25, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (26, 'Hawaii University', 'Hawaii');
insert into (schoolno, name, address) values (27, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (28, 'Massachusetts University', 'Massachusetts');
insert into (schoolno, name, address) values (29, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (30, 'Michigan University', 'Michigan');
insert into (schoolno, name, address) values (31, 'Nevada University', 'Nevada');
insert into (schoolno, name, address) values (32, 'Kansas University', 'Kansas');
insert into (schoolno, name, address) values (33, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (34, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (35, 'Nevada University', 'Nevada');
insert into (schoolno, name, address) values (36, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (37, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (38, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (39, 'Alaska University', 'Alaska');
insert into (schoolno, name, address) values (40, 'Indiana University', 'Indiana');
insert into (schoolno, name, address) values (41, 'Maryland University', 'Maryland');
insert into (schoolno, name, address) values (42, 'Nevada University', 'Nevada');
insert into (schoolno, name, address) values (43, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (44, 'Missouri University', 'Missouri');
insert into (schoolno, name, address) values (45, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (46, 'Massachusetts University', 'Massachusetts');
insert into (schoolno, name, address) values (47, 'Connecticut University', 'Connecticut');
insert into (schoolno, name, address) values (48, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (49, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (50, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (51, 'Tennessee University', 'Tennessee');
insert into (schoolno, name, address) values (52, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (53, 'Indiana University', 'Indiana');
insert into (schoolno, name, address) values (54, 'New Jersey University', 'New Jersey');
insert into (schoolno, name, address) values (55, 'Kentucky University', 'Kentucky');
insert into (schoolno, name, address) values (56, 'New Jersey University', 'New Jersey');
insert into (schoolno, name, address) values (57, 'Louisiana University', 'Louisiana');
insert into (schoolno, name, address) values (58, 'Michigan University', 'Michigan');
insert into (schoolno, name, address) values (59, 'West Virginia University', 'West Virginia');
insert into (schoolno, name, address) values (60, 'California University', 'California');
insert into (schoolno, name, address) values (61, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (62, 'Indiana University', 'Indiana');
insert into (schoolno, name, address) values (63, 'New Jersey University', 'New Jersey');
insert into (schoolno, name, address) values (64, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (65, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (66, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (67, 'Washington University', 'Washington');
insert into (schoolno, name, address) values (68, 'Indiana University', 'Indiana');
insert into (schoolno, name, address) values (69, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (70, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (71, 'California University', 'California');
insert into (schoolno, name, address) values (72, 'New Mexico University', 'New Mexico');
insert into (schoolno, name, address) values (73, 'Indiana University', 'Indiana');
insert into (schoolno, name, address) values (74, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (75, 'South Carolina University', 'South Carolina');
insert into (schoolno, name, address) values (76, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (77, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (78, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (79, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (80, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (81, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (82, 'New Hampshire University', 'New Hampshire');
insert into (schoolno, name, address) values (83, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (84, 'New Jersey University', 'New Jersey');
insert into (schoolno, name, address) values (85, 'Utah University', 'Utah');
insert into (schoolno, name, address) values (86, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (87, 'North Carolina University', 'North Carolina');
insert into (schoolno, name, address) values (88, 'Mississippi University', 'Mississippi');
insert into (schoolno, name, address) values (89, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (90, 'Missouri University', 'Missouri');
insert into (schoolno, name, address) values (91, 'Missouri University', 'Missouri');
insert into (schoolno, name, address) values (92, 'Tennessee University', 'Tennessee');
insert into (schoolno, name, address) values (93, 'Maryland University', 'Maryland');
insert into (schoolno, name, address) values (94, 'New Mexico University', 'New Mexico');
insert into (schoolno, name, address) values (95, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (96, 'Indiana University', 'Indiana');
insert into (schoolno, name, address) values (97, 'Nevada University', 'Nevada');
insert into (schoolno, name, address) values (98, 'California University', 'California');
insert into (schoolno, name, address) values (99, 'Illinois University', 'Illinois');
insert into (schoolno, name, address) values (100, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (101, 'New York University', 'New York');
insert into (schoolno, name, address) values (102, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (103, 'New Jersey University', 'New Jersey');
insert into (schoolno, name, address) values (104, 'Colorado University', 'Colorado');
insert into (schoolno, name, address) values (105, 'Maryland University', 'Maryland');
insert into (schoolno, name, address) values (106, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (107, 'California University', 'California');
insert into (schoolno, name, address) values (108, 'Oklahoma University', 'Oklahoma');
insert into (schoolno, name, address) values (109, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (110, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (111, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (112, 'Massachusetts University', 'Massachusetts');
insert into (schoolno, name, address) values (113, 'Kentucky University', 'Kentucky');
insert into (schoolno, name, address) values (114, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (115, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (116, 'California University', 'California');
insert into (schoolno, name, address) values (117, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (118, 'Washington University', 'Washington');
insert into (schoolno, name, address) values (119, 'Alabama University', 'Alabama');
insert into (schoolno, name, address) values (120, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (121, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (122, 'Michigan University', 'Michigan');
insert into (schoolno, name, address) values (123, 'South Carolina University', 'South Carolina');
insert into (schoolno, name, address) values (124, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (125, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (126, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (127, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (128, 'Oklahoma University', 'Oklahoma');
insert into (schoolno, name, address) values (129, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (130, 'Connecticut University', 'Connecticut');
insert into (schoolno, name, address) values (131, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (132, 'Illinois University', 'Illinois');
insert into (schoolno, name, address) values (133, 'South Carolina University', 'South Carolina');
insert into (schoolno, name, address) values (134, 'California University', 'California');
insert into (schoolno, name, address) values (135, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (136, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (137, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (138, 'Washington University', 'Washington');
insert into (schoolno, name, address) values (139, 'California University', 'California');
insert into (schoolno, name, address) values (140, 'Louisiana University', 'Louisiana');
insert into (schoolno, name, address) values (141, 'New Mexico University', 'New Mexico');
insert into (schoolno, name, address) values (142, 'Colorado University', 'Colorado');
insert into (schoolno, name, address) values (143, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (144, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (145, 'California University', 'California');
insert into (schoolno, name, address) values (146, 'New York University', 'New York');
insert into (schoolno, name, address) values (147, 'Illinois University', 'Illinois');
insert into (schoolno, name, address) values (148, 'Utah University', 'Utah');
insert into (schoolno, name, address) values (149, 'Indiana University', 'Indiana');
insert into (schoolno, name, address) values (150, 'Iowa University', 'Iowa');
insert into (schoolno, name, address) values (151, 'Kansas University', 'Kansas');
insert into (schoolno, name, address) values (152, 'New York University', 'New York');
insert into (schoolno, name, address) values (153, 'Idaho University', 'Idaho');
insert into (schoolno, name, address) values (154, 'Alabama University', 'Alabama');
insert into (schoolno, name, address) values (155, 'California University', 'California');
insert into (schoolno, name, address) values (156, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (157, 'Indiana University', 'Indiana');
insert into (schoolno, name, address) values (158, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (159, 'Oregon University', 'Oregon');
insert into (schoolno, name, address) values (160, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (161, 'Oklahoma University', 'Oklahoma');
insert into (schoolno, name, address) values (162, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (163, 'Indiana University', 'Indiana');
insert into (schoolno, name, address) values (164, 'North Carolina University', 'North Carolina');
insert into (schoolno, name, address) values (165, 'West Virginia University', 'West Virginia');
insert into (schoolno, name, address) values (166, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (167, 'Louisiana University', 'Louisiana');
insert into (schoolno, name, address) values (168, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (169, 'Colorado University', 'Colorado');
insert into (schoolno, name, address) values (170, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (171, 'New York University', 'New York');
insert into (schoolno, name, address) values (172, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (173, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (174, 'Oregon University', 'Oregon');
insert into (schoolno, name, address) values (175, 'Tennessee University', 'Tennessee');
insert into (schoolno, name, address) values (176, 'Michigan University', 'Michigan');
insert into (schoolno, name, address) values (177, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (178, 'North Carolina University', 'North Carolina');
insert into (schoolno, name, address) values (179, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (180, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (181, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (182, 'Missouri University', 'Missouri');
insert into (schoolno, name, address) values (183, 'Alaska University', 'Alaska');
insert into (schoolno, name, address) values (184, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (185, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (186, 'Colorado University', 'Colorado');
insert into (schoolno, name, address) values (187, 'California University', 'California');
insert into (schoolno, name, address) values (188, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (189, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (190, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (191, 'California University', 'California');
insert into (schoolno, name, address) values (192, 'New York University', 'New York');
insert into (schoolno, name, address) values (193, 'Maryland University', 'Maryland');
insert into (schoolno, name, address) values (194, 'New York University', 'New York');
insert into (schoolno, name, address) values (195, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (196, 'New York University', 'New York');
insert into (schoolno, name, address) values (197, 'Colorado University', 'Colorado');
insert into (schoolno, name, address) values (198, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (199, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (200, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (201, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (202, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (203, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (204, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (205, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (206, 'New Jersey University', 'New Jersey');
insert into (schoolno, name, address) values (207, 'Hawaii University', 'Hawaii');
insert into (schoolno, name, address) values (208, 'Colorado University', 'Colorado');
insert into (schoolno, name, address) values (209, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (210, 'Wisconsin University', 'Wisconsin');
insert into (schoolno, name, address) values (211, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (212, 'Massachusetts University', 'Massachusetts');
insert into (schoolno, name, address) values (213, 'Illinois University', 'Illinois');
insert into (schoolno, name, address) values (214, 'South Dakota University', 'South Dakota');
insert into (schoolno, name, address) values (215, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (216, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (217, 'Michigan University', 'Michigan');
insert into (schoolno, name, address) values (218, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (219, 'Nevada University', 'Nevada');
insert into (schoolno, name, address) values (220, 'New York University', 'New York');
insert into (schoolno, name, address) values (221, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (222, 'California University', 'California');
insert into (schoolno, name, address) values (223, 'South Carolina University', 'South Carolina');
insert into (schoolno, name, address) values (224, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (225, 'California University', 'California');
insert into (schoolno, name, address) values (226, 'California University', 'California');
insert into (schoolno, name, address) values (227, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (228, 'California University', 'California');
insert into (schoolno, name, address) values (229, 'Indiana University', 'Indiana');
insert into (schoolno, name, address) values (230, 'South Dakota University', 'South Dakota');
insert into (schoolno, name, address) values (231, 'Colorado University', 'Colorado');
insert into (schoolno, name, address) values (232, 'New Hampshire University', 'New Hampshire');
insert into (schoolno, name, address) values (233, 'Maryland University', 'Maryland');
insert into (schoolno, name, address) values (234, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (235, 'Michigan University', 'Michigan');
insert into (schoolno, name, address) values (236, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (237, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (238, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (239, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (240, 'California University', 'California');
insert into (schoolno, name, address) values (241, 'California University', 'California');
insert into (schoolno, name, address) values (242, 'Michigan University', 'Michigan');
insert into (schoolno, name, address) values (243, 'Alabama University', 'Alabama');
insert into (schoolno, name, address) values (244, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (245, 'Kansas University', 'Kansas');
insert into (schoolno, name, address) values (246, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (247, 'Utah University', 'Utah');
insert into (schoolno, name, address) values (248, 'Oregon University', 'Oregon');
insert into (schoolno, name, address) values (249, 'New York University', 'New York');
insert into (schoolno, name, address) values (250, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (251, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (252, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (253, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (254, 'Oregon University', 'Oregon');
insert into (schoolno, name, address) values (255, 'California University', 'California');
insert into (schoolno, name, address) values (256, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (257, 'Idaho University', 'Idaho');
insert into (schoolno, name, address) values (258, 'Connecticut University', 'Connecticut');
insert into (schoolno, name, address) values (259, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (260, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (261, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (262, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (263, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (264, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (265, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (266, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (267, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (268, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (269, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (270, 'California University', 'California');
insert into (schoolno, name, address) values (271, 'California University', 'California');
insert into (schoolno, name, address) values (272, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (273, 'Maryland University', 'Maryland');
insert into (schoolno, name, address) values (274, 'Kentucky University', 'Kentucky');
insert into (schoolno, name, address) values (275, 'Utah University', 'Utah');
insert into (schoolno, name, address) values (276, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (277, 'Indiana University', 'Indiana');
insert into (schoolno, name, address) values (278, 'Kentucky University', 'Kentucky');
insert into (schoolno, name, address) values (279, 'Oklahoma University', 'Oklahoma');
insert into (schoolno, name, address) values (280, 'New York University', 'New York');
insert into (schoolno, name, address) values (281, 'South Carolina University', 'South Carolina');
insert into (schoolno, name, address) values (282, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (283, 'Connecticut University', 'Connecticut');
insert into (schoolno, name, address) values (284, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (285, 'New Mexico University', 'New Mexico');
insert into (schoolno, name, address) values (286, 'California University', 'California');
insert into (schoolno, name, address) values (287, 'Alabama University', 'Alabama');
insert into (schoolno, name, address) values (288, 'South Carolina University', 'South Carolina');
insert into (schoolno, name, address) values (289, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (290, 'Colorado University', 'Colorado');
insert into (schoolno, name, address) values (291, 'California University', 'California');
insert into (schoolno, name, address) values (292, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (293, 'Hawaii University', 'Hawaii');
insert into (schoolno, name, address) values (294, 'North Carolina University', 'North Carolina');
insert into (schoolno, name, address) values (295, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (296, 'Tennessee University', 'Tennessee');
insert into (schoolno, name, address) values (297, 'Missouri University', 'Missouri');
insert into (schoolno, name, address) values (298, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (299, 'Nevada University', 'Nevada');
insert into (schoolno, name, address) values (300, 'Oregon University', 'Oregon');
insert into (schoolno, name, address) values (301, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (302, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (303, 'California University', 'California');
insert into (schoolno, name, address) values (304, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (305, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (306, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (307, 'New York University', 'New York');
insert into (schoolno, name, address) values (308, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (309, 'New York University', 'New York');
insert into (schoolno, name, address) values (310, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (311, 'Kansas University', 'Kansas');
insert into (schoolno, name, address) values (312, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (313, 'California University', 'California');
insert into (schoolno, name, address) values (314, 'Tennessee University', 'Tennessee');
insert into (schoolno, name, address) values (315, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (316, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (317, 'West Virginia University', 'West Virginia');
insert into (schoolno, name, address) values (318, 'New York University', 'New York');
insert into (schoolno, name, address) values (319, 'Oklahoma University', 'Oklahoma');
insert into (schoolno, name, address) values (320, 'Arkansas University', 'Arkansas');
insert into (schoolno, name, address) values (321, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (322, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (323, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (324, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (325, 'Kansas University', 'Kansas');
insert into (schoolno, name, address) values (326, 'North Carolina University', 'North Carolina');
insert into (schoolno, name, address) values (327, 'Oregon University', 'Oregon');
insert into (schoolno, name, address) values (328, 'Massachusetts University', 'Massachusetts');
insert into (schoolno, name, address) values (329, 'New York University', 'New York');
insert into (schoolno, name, address) values (330, 'California University', 'California');
insert into (schoolno, name, address) values (331, 'Idaho University', 'Idaho');
insert into (schoolno, name, address) values (332, 'California University', 'California');
insert into (schoolno, name, address) values (333, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (334, 'Louisiana University', 'Louisiana');
insert into (schoolno, name, address) values (335, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (336, 'Tennessee University', 'Tennessee');
insert into (schoolno, name, address) values (337, 'Hawaii University', 'Hawaii');
insert into (schoolno, name, address) values (338, 'California University', 'California');
insert into (schoolno, name, address) values (339, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (340, 'Idaho University', 'Idaho');
insert into (schoolno, name, address) values (341, 'California University', 'California');
insert into (schoolno, name, address) values (342, 'New York University', 'New York');
insert into (schoolno, name, address) values (343, 'North Carolina University', 'North Carolina');
insert into (schoolno, name, address) values (344, 'California University', 'California');
insert into (schoolno, name, address) values (345, 'North Carolina University', 'North Carolina');
insert into (schoolno, name, address) values (346, 'Maryland University', 'Maryland');
insert into (schoolno, name, address) values (347, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (348, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (349, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (350, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (351, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (352, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (353, 'Nevada University', 'Nevada');
insert into (schoolno, name, address) values (354, 'Oklahoma University', 'Oklahoma');
insert into (schoolno, name, address) values (355, 'Louisiana University', 'Louisiana');
insert into (schoolno, name, address) values (356, 'New York University', 'New York');
insert into (schoolno, name, address) values (357, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (358, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (359, 'South Carolina University', 'South Carolina');
insert into (schoolno, name, address) values (360, 'Maine University', 'Maine');
insert into (schoolno, name, address) values (361, 'Massachusetts University', 'Massachusetts');
insert into (schoolno, name, address) values (362, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (363, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (364, 'Oklahoma University', 'Oklahoma');
insert into (schoolno, name, address) values (365, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (366, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (367, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (368, 'Tennessee University', 'Tennessee');
insert into (schoolno, name, address) values (369, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (370, 'California University', 'California');
insert into (schoolno, name, address) values (371, 'Michigan University', 'Michigan');
insert into (schoolno, name, address) values (372, 'Maryland University', 'Maryland');
insert into (schoolno, name, address) values (373, 'Iowa University', 'Iowa');
insert into (schoolno, name, address) values (374, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (375, 'California University', 'California');
insert into (schoolno, name, address) values (376, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (377, 'California University', 'California');
insert into (schoolno, name, address) values (378, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (379, 'California University', 'California');
insert into (schoolno, name, address) values (380, 'North Carolina University', 'North Carolina');
insert into (schoolno, name, address) values (381, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (382, 'California University', 'California');
insert into (schoolno, name, address) values (383, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (384, 'California University', 'California');
insert into (schoolno, name, address) values (385, 'Louisiana University', 'Louisiana');
insert into (schoolno, name, address) values (386, 'Louisiana University', 'Louisiana');
insert into (schoolno, name, address) values (387, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (388, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (389, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (390, 'California University', 'California');
insert into (schoolno, name, address) values (391, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (392, 'Tennessee University', 'Tennessee');
insert into (schoolno, name, address) values (393, 'Nebraska University', 'Nebraska');
insert into (schoolno, name, address) values (394, 'Utah University', 'Utah');
insert into (schoolno, name, address) values (395, 'Alaska University', 'Alaska');
insert into (schoolno, name, address) values (396, 'Michigan University', 'Michigan');
insert into (schoolno, name, address) values (397, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (398, 'California University', 'California');
insert into (schoolno, name, address) values (399, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (400, 'Mississippi University', 'Mississippi');
insert into (schoolno, name, address) values (401, 'North Carolina University', 'North Carolina');
insert into (schoolno, name, address) values (402, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (403, 'Oklahoma University', 'Oklahoma');
insert into (schoolno, name, address) values (404, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (405, 'California University', 'California');
insert into (schoolno, name, address) values (406, 'South Carolina University', 'South Carolina');
insert into (schoolno, name, address) values (407, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (408, 'New York University', 'New York');
insert into (schoolno, name, address) values (409, 'Tennessee University', 'Tennessee');
insert into (schoolno, name, address) values (410, 'North Carolina University', 'North Carolina');
insert into (schoolno, name, address) values (411, 'Missouri University', 'Missouri');
insert into (schoolno, name, address) values (412, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (413, 'Massachusetts University', 'Massachusetts');
insert into (schoolno, name, address) values (414, 'California University', 'California');
insert into (schoolno, name, address) values (415, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (416, 'California University', 'California');
insert into (schoolno, name, address) values (417, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (418, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (419, 'California University', 'California');
insert into (schoolno, name, address) values (420, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (421, 'California University', 'California');
insert into (schoolno, name, address) values (422, 'Connecticut University', 'Connecticut');
insert into (schoolno, name, address) values (423, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (424, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (425, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (426, 'Illinois University', 'Illinois');
insert into (schoolno, name, address) values (427, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (428, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (429, 'Louisiana University', 'Louisiana');
insert into (schoolno, name, address) values (430, 'Michigan University', 'Michigan');
insert into (schoolno, name, address) values (431, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (432, 'Michigan University', 'Michigan');
insert into (schoolno, name, address) values (433, 'California University', 'California');
insert into (schoolno, name, address) values (434, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (435, 'South Carolina University', 'South Carolina');
insert into (schoolno, name, address) values (436, 'Tennessee University', 'Tennessee');
insert into (schoolno, name, address) values (437, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (438, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (439, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (440, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (441, 'New York University', 'New York');
insert into (schoolno, name, address) values (442, 'Oklahoma University', 'Oklahoma');
insert into (schoolno, name, address) values (443, 'Illinois University', 'Illinois');
insert into (schoolno, name, address) values (444, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (445, 'Tennessee University', 'Tennessee');
insert into (schoolno, name, address) values (446, 'Iowa University', 'Iowa');
insert into (schoolno, name, address) values (447, 'Colorado University', 'Colorado');
insert into (schoolno, name, address) values (448, 'New York University', 'New York');
insert into (schoolno, name, address) values (449, 'California University', 'California');
insert into (schoolno, name, address) values (450, 'West Virginia University', 'West Virginia');
insert into (schoolno, name, address) values (451, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (452, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (453, 'Iowa University', 'Iowa');
insert into (schoolno, name, address) values (454, 'Indiana University', 'Indiana');
insert into (schoolno, name, address) values (455, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (456, 'Massachusetts University', 'Massachusetts');
insert into (schoolno, name, address) values (457, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (458, 'Michigan University', 'Michigan');
insert into (schoolno, name, address) values (459, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (460, 'Louisiana University', 'Louisiana');
insert into (schoolno, name, address) values (461, 'Indiana University', 'Indiana');
insert into (schoolno, name, address) values (462, 'Alabama University', 'Alabama');
insert into (schoolno, name, address) values (463, 'California University', 'California');
insert into (schoolno, name, address) values (464, 'New York University', 'New York');
insert into (schoolno, name, address) values (465, 'Tennessee University', 'Tennessee');
insert into (schoolno, name, address) values (466, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (467, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (468, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (469, 'Iowa University', 'Iowa');
insert into (schoolno, name, address) values (470, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (471, 'New York University', 'New York');
insert into (schoolno, name, address) values (472, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (473, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (474, 'Oregon University', 'Oregon');
insert into (schoolno, name, address) values (475, 'Missouri University', 'Missouri');
insert into (schoolno, name, address) values (476, 'Arkansas University', 'Arkansas');
insert into (schoolno, name, address) values (477, 'North Carolina University', 'North Carolina');
insert into (schoolno, name, address) values (478, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (479, 'Connecticut University', 'Connecticut');
insert into (schoolno, name, address) values (480, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (481, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (482, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (483, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (484, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (485, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (486, 'California University', 'California');
insert into (schoolno, name, address) values (487, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (488, 'California University', 'California');
insert into (schoolno, name, address) values (489, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (490, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (491, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (492, 'Washington University', 'Washington');
insert into (schoolno, name, address) values (493, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (494, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (495, 'New York University', 'New York');
insert into (schoolno, name, address) values (496, 'Montana University', 'Montana');
insert into (schoolno, name, address) values (497, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (498, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (499, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (500, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (501, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (502, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (503, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (504, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (505, 'Illinois University', 'Illinois');
insert into (schoolno, name, address) values (506, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (507, 'Alabama University', 'Alabama');
insert into (schoolno, name, address) values (508, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (509, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (510, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (511, 'Idaho University', 'Idaho');
insert into (schoolno, name, address) values (512, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (513, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (514, 'Tennessee University', 'Tennessee');
insert into (schoolno, name, address) values (515, 'Missouri University', 'Missouri');
insert into (schoolno, name, address) values (516, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (517, 'Massachusetts University', 'Massachusetts');
insert into (schoolno, name, address) values (518, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (519, 'California University', 'California');
insert into (schoolno, name, address) values (520, 'Arkansas University', 'Arkansas');
insert into (schoolno, name, address) values (521, 'Tennessee University', 'Tennessee');
insert into (schoolno, name, address) values (522, 'Montana University', 'Montana');
insert into (schoolno, name, address) values (523, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (524, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (525, 'California University', 'California');
insert into (schoolno, name, address) values (526, 'Massachusetts University', 'Massachusetts');
insert into (schoolno, name, address) values (527, 'Alabama University', 'Alabama');
insert into (schoolno, name, address) values (528, 'California University', 'California');
insert into (schoolno, name, address) values (529, 'Oklahoma University', 'Oklahoma');
insert into (schoolno, name, address) values (530, 'West Virginia University', 'West Virginia');
insert into (schoolno, name, address) values (531, 'Illinois University', 'Illinois');
insert into (schoolno, name, address) values (532, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (533, 'Missouri University', 'Missouri');
insert into (schoolno, name, address) values (534, 'California University', 'California');
insert into (schoolno, name, address) values (535, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (536, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (537, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (538, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (539, 'New York University', 'New York');
insert into (schoolno, name, address) values (540, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (541, 'Washington University', 'Washington');
insert into (schoolno, name, address) values (542, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (543, 'Louisiana University', 'Louisiana');
insert into (schoolno, name, address) values (544, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (545, 'Missouri University', 'Missouri');
insert into (schoolno, name, address) values (546, 'Louisiana University', 'Louisiana');
insert into (schoolno, name, address) values (547, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (548, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (549, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (550, 'Montana University', 'Montana');
insert into (schoolno, name, address) values (551, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (552, 'New York University', 'New York');
insert into (schoolno, name, address) values (553, 'California University', 'California');
insert into (schoolno, name, address) values (554, 'North Carolina University', 'North Carolina');
insert into (schoolno, name, address) values (555, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (556, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (557, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (558, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (559, 'California University', 'California');
insert into (schoolno, name, address) values (560, 'Louisiana University', 'Louisiana');
insert into (schoolno, name, address) values (561, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (562, 'California University', 'California');
insert into (schoolno, name, address) values (563, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (564, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (565, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (566, 'Alabama University', 'Alabama');
insert into (schoolno, name, address) values (567, 'Connecticut University', 'Connecticut');
insert into (schoolno, name, address) values (568, 'New York University', 'New York');
insert into (schoolno, name, address) values (569, 'North Carolina University', 'North Carolina');
insert into (schoolno, name, address) values (570, 'California University', 'California');
insert into (schoolno, name, address) values (571, 'California University', 'California');
insert into (schoolno, name, address) values (572, 'Oklahoma University', 'Oklahoma');
insert into (schoolno, name, address) values (573, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (574, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (575, 'California University', 'California');
insert into (schoolno, name, address) values (576, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (577, 'Wisconsin University', 'Wisconsin');
insert into (schoolno, name, address) values (578, 'California University', 'California');
insert into (schoolno, name, address) values (579, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (580, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (581, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (582, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (583, 'New York University', 'New York');
insert into (schoolno, name, address) values (584, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (585, 'Maryland University', 'Maryland');
insert into (schoolno, name, address) values (586, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (587, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (588, 'Mississippi University', 'Mississippi');
insert into (schoolno, name, address) values (589, 'Kansas University', 'Kansas');
insert into (schoolno, name, address) values (590, 'Tennessee University', 'Tennessee');
insert into (schoolno, name, address) values (591, 'North Carolina University', 'North Carolina');
insert into (schoolno, name, address) values (592, 'California University', 'California');
insert into (schoolno, name, address) values (593, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (594, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (595, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (596, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (597, 'New York University', 'New York');
insert into (schoolno, name, address) values (598, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (599, 'North Carolina University', 'North Carolina');
insert into (schoolno, name, address) values (600, 'Arkansas University', 'Arkansas');
insert into (schoolno, name, address) values (601, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (602, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (603, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (604, 'Mississippi University', 'Mississippi');
insert into (schoolno, name, address) values (605, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (606, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (607, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (608, 'California University', 'California');
insert into (schoolno, name, address) values (609, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (610, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (611, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (612, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (613, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (614, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (615, 'Colorado University', 'Colorado');
insert into (schoolno, name, address) values (616, 'Louisiana University', 'Louisiana');
insert into (schoolno, name, address) values (617, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (618, 'Kentucky University', 'Kentucky');
insert into (schoolno, name, address) values (619, 'California University', 'California');
insert into (schoolno, name, address) values (620, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (621, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (622, 'Maine University', 'Maine');
insert into (schoolno, name, address) values (623, 'Colorado University', 'Colorado');
insert into (schoolno, name, address) values (624, 'California University', 'California');
insert into (schoolno, name, address) values (625, 'California University', 'California');
insert into (schoolno, name, address) values (626, 'South Carolina University', 'South Carolina');
insert into (schoolno, name, address) values (627, 'Idaho University', 'Idaho');
insert into (schoolno, name, address) values (628, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (629, 'California University', 'California');
insert into (schoolno, name, address) values (630, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (631, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (632, 'Washington University', 'Washington');
insert into (schoolno, name, address) values (633, 'Indiana University', 'Indiana');
insert into (schoolno, name, address) values (634, 'Nevada University', 'Nevada');
insert into (schoolno, name, address) values (635, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (636, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (637, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (638, 'Missouri University', 'Missouri');
insert into (schoolno, name, address) values (639, 'Indiana University', 'Indiana');
insert into (schoolno, name, address) values (640, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (641, 'Colorado University', 'Colorado');
insert into (schoolno, name, address) values (642, 'Tennessee University', 'Tennessee');
insert into (schoolno, name, address) values (643, 'Wisconsin University', 'Wisconsin');
insert into (schoolno, name, address) values (644, 'Utah University', 'Utah');
insert into (schoolno, name, address) values (645, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (646, 'Oklahoma University', 'Oklahoma');
insert into (schoolno, name, address) values (647, 'California University', 'California');
insert into (schoolno, name, address) values (648, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (649, 'Illinois University', 'Illinois');
insert into (schoolno, name, address) values (650, 'California University', 'California');
insert into (schoolno, name, address) values (651, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (652, 'California University', 'California');
insert into (schoolno, name, address) values (653, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (654, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (655, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (656, 'North Carolina University', 'North Carolina');
insert into (schoolno, name, address) values (657, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (658, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (659, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (660, 'Washington University', 'Washington');
insert into (schoolno, name, address) values (661, 'Kentucky University', 'Kentucky');
insert into (schoolno, name, address) values (662, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (663, 'Nevada University', 'Nevada');
insert into (schoolno, name, address) values (664, 'New Jersey University', 'New Jersey');
insert into (schoolno, name, address) values (665, 'Louisiana University', 'Louisiana');
insert into (schoolno, name, address) values (666, 'Connecticut University', 'Connecticut');
insert into (schoolno, name, address) values (667, 'Delaware University', 'Delaware');
insert into (schoolno, name, address) values (668, 'California University', 'California');
insert into (schoolno, name, address) values (669, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (670, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (671, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (672, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (673, 'Colorado University', 'Colorado');
insert into (schoolno, name, address) values (674, 'Oklahoma University', 'Oklahoma');
insert into (schoolno, name, address) values (675, 'New York University', 'New York');
insert into (schoolno, name, address) values (676, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (677, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (678, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (679, 'Missouri University', 'Missouri');
insert into (schoolno, name, address) values (680, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (681, 'Illinois University', 'Illinois');
insert into (schoolno, name, address) values (682, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (683, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (684, 'North Carolina University', 'North Carolina');
insert into (schoolno, name, address) values (685, 'New York University', 'New York');
insert into (schoolno, name, address) values (686, 'Oklahoma University', 'Oklahoma');
insert into (schoolno, name, address) values (687, 'Alabama University', 'Alabama');
insert into (schoolno, name, address) values (688, 'Iowa University', 'Iowa');
insert into (schoolno, name, address) values (689, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (690, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (691, 'Michigan University', 'Michigan');
insert into (schoolno, name, address) values (692, 'Utah University', 'Utah');
insert into (schoolno, name, address) values (693, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (694, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (695, 'California University', 'California');
insert into (schoolno, name, address) values (696, 'South Carolina University', 'South Carolina');
insert into (schoolno, name, address) values (697, 'Tennessee University', 'Tennessee');
insert into (schoolno, name, address) values (698, 'Missouri University', 'Missouri');
insert into (schoolno, name, address) values (699, 'California University', 'California');
insert into (schoolno, name, address) values (700, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (701, 'Tennessee University', 'Tennessee');
insert into (schoolno, name, address) values (702, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (703, 'Indiana University', 'Indiana');
insert into (schoolno, name, address) values (704, 'Kansas University', 'Kansas');
insert into (schoolno, name, address) values (705, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (706, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (707, 'West Virginia University', 'West Virginia');
insert into (schoolno, name, address) values (708, 'Michigan University', 'Michigan');
insert into (schoolno, name, address) values (709, 'Louisiana University', 'Louisiana');
insert into (schoolno, name, address) values (710, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (711, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (712, 'Oklahoma University', 'Oklahoma');
insert into (schoolno, name, address) values (713, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (714, 'Connecticut University', 'Connecticut');
insert into (schoolno, name, address) values (715, 'Nebraska University', 'Nebraska');
insert into (schoolno, name, address) values (716, 'Nevada University', 'Nevada');
insert into (schoolno, name, address) values (717, 'Washington University', 'Washington');
insert into (schoolno, name, address) values (718, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (719, 'Connecticut University', 'Connecticut');
insert into (schoolno, name, address) values (720, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (721, 'Wisconsin University', 'Wisconsin');
insert into (schoolno, name, address) values (722, 'Illinois University', 'Illinois');
insert into (schoolno, name, address) values (723, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (724, 'Alabama University', 'Alabama');
insert into (schoolno, name, address) values (725, 'Louisiana University', 'Louisiana');
insert into (schoolno, name, address) values (726, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (727, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (728, 'Alaska University', 'Alaska');
insert into (schoolno, name, address) values (729, 'California University', 'California');
insert into (schoolno, name, address) values (730, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (731, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (732, 'Colorado University', 'Colorado');
insert into (schoolno, name, address) values (733, 'Colorado University', 'Colorado');
insert into (schoolno, name, address) values (734, 'California University', 'California');
insert into (schoolno, name, address) values (735, 'California University', 'California');
insert into (schoolno, name, address) values (736, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (737, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (738, 'Nevada University', 'Nevada');
insert into (schoolno, name, address) values (739, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (740, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (741, 'New York University', 'New York');
insert into (schoolno, name, address) values (742, 'Louisiana University', 'Louisiana');
insert into (schoolno, name, address) values (743, 'Michigan University', 'Michigan');
insert into (schoolno, name, address) values (744, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (745, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (746, 'New York University', 'New York');
insert into (schoolno, name, address) values (747, 'Alaska University', 'Alaska');
insert into (schoolno, name, address) values (748, 'Louisiana University', 'Louisiana');
insert into (schoolno, name, address) values (749, 'Alabama University', 'Alabama');
insert into (schoolno, name, address) values (750, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (751, 'New York University', 'New York');
insert into (schoolno, name, address) values (752, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (753, 'New York University', 'New York');
insert into (schoolno, name, address) values (754, 'California University', 'California');
insert into (schoolno, name, address) values (755, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (756, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (757, 'New York University', 'New York');
insert into (schoolno, name, address) values (758, 'Michigan University', 'Michigan');
insert into (schoolno, name, address) values (759, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (760, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (761, 'New York University', 'New York');
insert into (schoolno, name, address) values (762, 'Missouri University', 'Missouri');
insert into (schoolno, name, address) values (763, 'New York University', 'New York');
insert into (schoolno, name, address) values (764, 'Oklahoma University', 'Oklahoma');
insert into (schoolno, name, address) values (765, 'Kentucky University', 'Kentucky');
insert into (schoolno, name, address) values (766, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (767, 'Colorado University', 'Colorado');
insert into (schoolno, name, address) values (768, 'North Carolina University', 'North Carolina');
insert into (schoolno, name, address) values (769, 'California University', 'California');
insert into (schoolno, name, address) values (770, 'New York University', 'New York');
insert into (schoolno, name, address) values (771, 'Connecticut University', 'Connecticut');
insert into (schoolno, name, address) values (772, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (773, 'Missouri University', 'Missouri');
insert into (schoolno, name, address) values (774, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (775, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (776, 'Michigan University', 'Michigan');
insert into (schoolno, name, address) values (777, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (778, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (779, 'Alabama University', 'Alabama');
insert into (schoolno, name, address) values (780, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (781, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (782, 'Colorado University', 'Colorado');
insert into (schoolno, name, address) values (783, 'Kentucky University', 'Kentucky');
insert into (schoolno, name, address) values (784, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (785, 'North Dakota University', 'North Dakota');
insert into (schoolno, name, address) values (786, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (787, 'California University', 'California');
insert into (schoolno, name, address) values (788, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (789, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (790, 'Oregon University', 'Oregon');
insert into (schoolno, name, address) values (791, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (792, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (793, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (794, 'New Mexico University', 'New Mexico');
insert into (schoolno, name, address) values (795, 'New Jersey University', 'New Jersey');
insert into (schoolno, name, address) values (796, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (797, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (798, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (799, 'Utah University', 'Utah');
insert into (schoolno, name, address) values (800, 'Missouri University', 'Missouri');
insert into (schoolno, name, address) values (801, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (802, 'California University', 'California');
insert into (schoolno, name, address) values (803, 'California University', 'California');
insert into (schoolno, name, address) values (804, 'New Jersey University', 'New Jersey');
insert into (schoolno, name, address) values (805, 'Iowa University', 'Iowa');
insert into (schoolno, name, address) values (806, 'California University', 'California');
insert into (schoolno, name, address) values (807, 'Indiana University', 'Indiana');
insert into (schoolno, name, address) values (808, 'Nevada University', 'Nevada');
insert into (schoolno, name, address) values (809, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (810, 'North Carolina University', 'North Carolina');
insert into (schoolno, name, address) values (811, 'Maryland University', 'Maryland');
insert into (schoolno, name, address) values (812, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (813, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (814, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (815, 'Missouri University', 'Missouri');
insert into (schoolno, name, address) values (816, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (817, 'Kentucky University', 'Kentucky');
insert into (schoolno, name, address) values (818, 'California University', 'California');
insert into (schoolno, name, address) values (819, 'Missouri University', 'Missouri');
insert into (schoolno, name, address) values (820, 'Hawaii University', 'Hawaii');
insert into (schoolno, name, address) values (821, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (822, 'New York University', 'New York');
insert into (schoolno, name, address) values (823, 'California University', 'California');
insert into (schoolno, name, address) values (824, 'Illinois University', 'Illinois');
insert into (schoolno, name, address) values (825, 'Connecticut University', 'Connecticut');
insert into (schoolno, name, address) values (826, 'Kentucky University', 'Kentucky');
insert into (schoolno, name, address) values (827, 'California University', 'California');
insert into (schoolno, name, address) values (828, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (829, 'New York University', 'New York');
insert into (schoolno, name, address) values (830, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (831, 'Illinois University', 'Illinois');
insert into (schoolno, name, address) values (832, 'Illinois University', 'Illinois');
insert into (schoolno, name, address) values (833, 'Oklahoma University', 'Oklahoma');
insert into (schoolno, name, address) values (834, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (835, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (836, 'Kentucky University', 'Kentucky');
insert into (schoolno, name, address) values (837, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (838, 'Illinois University', 'Illinois');
insert into (schoolno, name, address) values (839, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (840, 'Colorado University', 'Colorado');
insert into (schoolno, name, address) values (841, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (842, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (843, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (844, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (845, 'North Carolina University', 'North Carolina');
insert into (schoolno, name, address) values (846, 'California University', 'California');
insert into (schoolno, name, address) values (847, 'New York University', 'New York');
insert into (schoolno, name, address) values (848, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (849, 'California University', 'California');
insert into (schoolno, name, address) values (850, 'Oklahoma University', 'Oklahoma');
insert into (schoolno, name, address) values (851, 'West Virginia University', 'West Virginia');
insert into (schoolno, name, address) values (852, 'Massachusetts University', 'Massachusetts');
insert into (schoolno, name, address) values (853, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (854, 'Nevada University', 'Nevada');
insert into (schoolno, name, address) values (855, 'Kansas University', 'Kansas');
insert into (schoolno, name, address) values (856, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (857, 'Georgia University', 'Georgia');
insert into (schoolno, name, address) values (858, 'Colorado University', 'Colorado');
insert into (schoolno, name, address) values (859, 'New Jersey University', 'New Jersey');
insert into (schoolno, name, address) values (860, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (861, 'Iowa University', 'Iowa');
insert into (schoolno, name, address) values (862, 'Montana University', 'Montana');
insert into (schoolno, name, address) values (863, 'New York University', 'New York');
insert into (schoolno, name, address) values (864, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (865, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (866, 'West Virginia University', 'West Virginia');
insert into (schoolno, name, address) values (867, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (868, 'Missouri University', 'Missouri');
insert into (schoolno, name, address) values (869, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (870, 'Tennessee University', 'Tennessee');
insert into (schoolno, name, address) values (871, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (872, 'California University', 'California');
insert into (schoolno, name, address) values (873, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (874, 'New York University', 'New York');
insert into (schoolno, name, address) values (875, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (876, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (877, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (878, 'Connecticut University', 'Connecticut');
insert into (schoolno, name, address) values (879, 'Connecticut University', 'Connecticut');
insert into (schoolno, name, address) values (880, 'Kansas University', 'Kansas');
insert into (schoolno, name, address) values (881, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (882, 'New York University', 'New York');
insert into (schoolno, name, address) values (883, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (884, 'New York University', 'New York');
insert into (schoolno, name, address) values (885, 'Illinois University', 'Illinois');
insert into (schoolno, name, address) values (886, 'Iowa University', 'Iowa');
insert into (schoolno, name, address) values (887, 'New York University', 'New York');
insert into (schoolno, name, address) values (888, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (889, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (890, 'Kansas University', 'Kansas');
insert into (schoolno, name, address) values (891, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (892, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (893, 'Alaska University', 'Alaska');
insert into (schoolno, name, address) values (894, 'Illinois University', 'Illinois');
insert into (schoolno, name, address) values (895, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (896, 'Nebraska University', 'Nebraska');
insert into (schoolno, name, address) values (897, 'Michigan University', 'Michigan');
insert into (schoolno, name, address) values (898, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (899, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (900, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (901, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (902, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (903, 'Colorado University', 'Colorado');
insert into (schoolno, name, address) values (904, 'California University', 'California');
insert into (schoolno, name, address) values (905, 'Arkansas University', 'Arkansas');
insert into (schoolno, name, address) values (906, 'Hawaii University', 'Hawaii');
insert into (schoolno, name, address) values (907, 'California University', 'California');
insert into (schoolno, name, address) values (908, 'Massachusetts University', 'Massachusetts');
insert into (schoolno, name, address) values (909, 'Colorado University', 'Colorado');
insert into (schoolno, name, address) values (910, 'North Carolina University', 'North Carolina');
insert into (schoolno, name, address) values (911, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (912, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (913, 'California University', 'California');
insert into (schoolno, name, address) values (914, 'Illinois University', 'Illinois');
insert into (schoolno, name, address) values (915, 'South Dakota University', 'South Dakota');
insert into (schoolno, name, address) values (916, 'Utah University', 'Utah');
insert into (schoolno, name, address) values (917, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (918, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (919, 'New York University', 'New York');
insert into (schoolno, name, address) values (920, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (921, 'California University', 'California');
insert into (schoolno, name, address) values (922, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (923, 'Oregon University', 'Oregon');
insert into (schoolno, name, address) values (924, 'Iowa University', 'Iowa');
insert into (schoolno, name, address) values (925, 'Wisconsin University', 'Wisconsin');
insert into (schoolno, name, address) values (926, 'California University', 'California');
insert into (schoolno, name, address) values (927, 'Tennessee University', 'Tennessee');
insert into (schoolno, name, address) values (928, 'California University', 'California');
insert into (schoolno, name, address) values (929, 'Illinois University', 'Illinois');
insert into (schoolno, name, address) values (930, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (931, 'Michigan University', 'Michigan');
insert into (schoolno, name, address) values (932, 'Louisiana University', 'Louisiana');
insert into (schoolno, name, address) values (933, 'Alabama University', 'Alabama');
insert into (schoolno, name, address) values (934, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (935, 'Michigan University', 'Michigan');
insert into (schoolno, name, address) values (936, 'Illinois University', 'Illinois');
insert into (schoolno, name, address) values (937, 'New York University', 'New York');
insert into (schoolno, name, address) values (938, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (939, 'Idaho University', 'Idaho');
insert into (schoolno, name, address) values (940, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (941, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (942, 'Michigan University', 'Michigan');
insert into (schoolno, name, address) values (943, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (944, 'California University', 'California');
insert into (schoolno, name, address) values (945, 'Washington University', 'Washington');
insert into (schoolno, name, address) values (946, 'Minnesota University', 'Minnesota');
insert into (schoolno, name, address) values (947, 'Massachusetts University', 'Massachusetts');
insert into (schoolno, name, address) values (948, 'California University', 'California');
insert into (schoolno, name, address) values (949, 'Massachusetts University', 'Massachusetts');
insert into (schoolno, name, address) values (950, 'New Jersey University', 'New Jersey');
insert into (schoolno, name, address) values (951, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (952, 'Indiana University', 'Indiana');
insert into (schoolno, name, address) values (953, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (954, 'North Dakota University', 'North Dakota');
insert into (schoolno, name, address) values (955, 'Indiana University', 'Indiana');
insert into (schoolno, name, address) values (956, 'New York University', 'New York');
insert into (schoolno, name, address) values (957, 'Kansas University', 'Kansas');
insert into (schoolno, name, address) values (958, 'Tennessee University', 'Tennessee');
insert into (schoolno, name, address) values (959, 'Missouri University', 'Missouri');
insert into (schoolno, name, address) values (960, 'New Jersey University', 'New Jersey');
insert into (schoolno, name, address) values (961, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (962, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (963, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (964, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (965, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (966, 'California University', 'California');
insert into (schoolno, name, address) values (967, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (968, 'Oklahoma University', 'Oklahoma');
insert into (schoolno, name, address) values (969, 'District of Columbia University', 'District of Columbia');
insert into (schoolno, name, address) values (970, 'California University', 'California');
insert into (schoolno, name, address) values (971, 'Ohio University', 'Ohio');
insert into (schoolno, name, address) values (972, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (973, 'Illinois University', 'Illinois');
insert into (schoolno, name, address) values (974, 'Louisiana University', 'Louisiana');
insert into (schoolno, name, address) values (975, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (976, 'Louisiana University', 'Louisiana');
insert into (schoolno, name, address) values (977, 'New Mexico University', 'New Mexico');
insert into (schoolno, name, address) values (978, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (979, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (980, 'Kansas University', 'Kansas');
insert into (schoolno, name, address) values (981, 'Massachusetts University', 'Massachusetts');
insert into (schoolno, name, address) values (982, 'Florida University', 'Florida');
insert into (schoolno, name, address) values (983, 'Pennsylvania University', 'Pennsylvania');
insert into (schoolno, name, address) values (984, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (985, 'Louisiana University', 'Louisiana');
insert into (schoolno, name, address) values (986, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (987, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (988, 'California University', 'California');
insert into (schoolno, name, address) values (989, 'Arizona University', 'Arizona');
insert into (schoolno, name, address) values (990, 'Tennessee University', 'Tennessee');
insert into (schoolno, name, address) values (991, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (992, 'Alabama University', 'Alabama');
insert into (schoolno, name, address) values (993, 'Nevada University', 'Nevada');
insert into (schoolno, name, address) values (994, 'California University', 'California');
insert into (schoolno, name, address) values (995, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (996, 'Virginia University', 'Virginia');
insert into (schoolno, name, address) values (997, 'Texas University', 'Texas');
insert into (schoolno, name, address) values (998, 'California University', 'California');
insert into (schoolno, name, address) values (999, 'North Carolina University', 'North Carolina');
insert into (schoolno, name, address) values (1000, 'Virginia University', 'Virginia');
